language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson libgranite-dev libgtk-3-dev libswitchboard-2.0-dev valac"

install:
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"

script:
 - echo BUILDS PASSED
